robot_state_publisher:
  ros__parameters:
    use_sim_time: true
    robot_description: |-
      <?xml version="1.0" encoding="utf-8"?>
      <!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
           Commit Version: 1.6.0-4-g7f85cfe  Build Version: 1.6.7995.38578
           For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
      <robot
        name="sim_Assem.SLDASM">
        <link
          name="base_link">
          <inertial>
            <origin
              xyz="0.34206 -0.05604 0.22506"
              rpy="0 0 0" />
            <mass
              value="14.793" />
            <inertia
              ixx="0.11862"
              ixy="-7.5813E-05"
              ixz="-7.972E-05"
              iyy="0.77188"
              iyz="-8.037E-05"
              izz="0.75786" />
          </inertial>
          <visual>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/base_link.STL" />
            </geometry>
            <material
              name="">
              <color
                rgba="0.79216 0.81961 0.93333 1" />
            </material>
          </visual>
          <collision>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/base_link.STL" />
            </geometry>
          </collision>
        </link>
        <link
          name="link1">
          <inertial>
            <origin
              xyz="0.05303 0.076941 -0.048359"
              rpy="0 0 0" />
            <mass
              value="1.2717" />
            <inertia
              ixx="0.008753"
              ixy="0.0001547"
              ixz="1.5204E-06"
              iyy="0.00091753"
              iyz="-7.5753E-05"
              izz="0.0094083" />
          </inertial>
          <visual>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link1.STL" />
            </geometry>
            <material
              name="">
              <color
                rgba="0.79216 0.81961 0.93333 1" />
            </material>
          </visual>
          <collision>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link1.STL" />
            </geometry>
          </collision>
        </link>
        <joint
          name="joint1"
          type="prismatic">
          <origin
            xyz="0 0 0"
            rpy="0 0 0" />
          <parent
            link="base_link" />
          <child
            link="link1" />
          <axis
            xyz="1 0 0" />
          <limit
            lower="0"
            upper="500"
            effort="0"
            velocity="0" />
        </joint>
        <link
          name="link2">
          <inertial>
            <origin
              xyz="0.10476 0.12206 -0.15295"
              rpy="0 0 0" />
            <mass
              value="0.55701" />
            <inertia
              ixx="0.001068"
              ixy="-1.5274E-06"
              ixz="2.2009E-05"
              iyy="0.0010653"
              iyz="-3.0878E-06"
              izz="0.00025901" />
          </inertial>
          <visual>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link2.STL" />
            </geometry>
            <material
              name="">
              <color
                rgba="0.79216 0.81961 0.93333 1" />
            </material>
          </visual>
          <collision>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link2.STL" />
            </geometry>
          </collision>
        </link>
        <joint
          name="joint2"
          type="prismatic">
          <origin
            xyz="0 0 0"
            rpy="0 0 0" />
          <parent
            link="link1" />
          <child
            link="link2" />
          <axis
            xyz="0 -1 0" />
          <limit
            lower="0"
            upper="195"
            effort="0"
            velocity="0.5" />
        </joint>
        <link
          name="link3">
          <inertial>
            <origin
              xyz="0.15464 0.12214 -0.10245"
              rpy="0 0 0" />
            <mass
              value="0.17487" />
            <inertia
              ixx="0.00019395"
              ixy="9.1119E-09"
              ixz="2.1314E-08"
              iyy="0.00015857"
              iyz="-7.1182E-10"
              izz="5.0461E-05" />
          </inertial>
          <visual>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link3.STL" />
            </geometry>
            <material
              name="">
              <color
                rgba="0.79216 0.81961 0.93333 1" />
            </material>
          </visual>
          <collision>
            <origin
              xyz="0 0 0"
              rpy="0 0 0" />
            <geometry>
              <mesh
                filename="/meshes/link3.STL" />
            </geometry>
          </collision>
        </link>
        <joint
          name="joint3"
          type="prismatic">
          <origin
            xyz="0 0 0"
            rpy="0 0 0" />
          <parent
            link="link2" />
          <child
            link="link3" />
          <axis
            xyz="0 0 -1" />
          <limit
            lower="0"
            upper="60"
            effort="0"
            velocity="0.5" />
        </joint>
        <ros2_control name="GazeboSystem" type="system">
          <hardware>
            <plugin>ign_ros2_control/IgnitionSystem</plugin>
          </hardware>
          <joint name="joint1">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
          </joint>
          <joint name="joint2">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
          </joint>
          <joint name="joint3">
            <command_interface name="position" />
            <state_interface name="position" />
            <state_interface name="velocity" />
          </joint>
        </ros2_control>
      </robot>
